### ISSUE TITLE
UnitOfWork Implementation

### ISSUE THREAD

**Issue by ffernandolima** [andreluizsecco/UnitOfWork.BookStore#1]
Sharing my complete data access implementation for EntityFrameworkCore which includes UnitOfWork, Repository, QueryBuilder, AutoHistory and other patterns/features.

Please check it out: https://github.com/ffernandolima/ef-core-data-access/tree/ef-core-3

Feel free to provide any kind of contribution, usage or sharing about it.

Thanks!

**Comment by andreluizsecco** [comment]
Cool @ffernandolima! Keep going :)

This repository is just a didactic and lean example of the Unit of Work pattern.
